name = "togethersystems"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "togethersystems"

[env.production.vars]
ENVIRONMENT = "production"

