name = "togethersystems"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# Pages Configuration
pages_build_output_dir = "."

[env.production]
name = "togethersystems"

[env.production.vars]
ENVIRONMENT = "production"

